version: "2.4"

services:
  gatsby:
    build:
      context: .
      target: development
    entrypoint: echo
    command:
      - Please use `make dshell`
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:8000
